name: "CI"
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "37 0 * * 0"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ubuntu_version: "20.04"
            llvm_version: 11
          - ubuntu_version: "20.04"
            llvm_version: 12
          - ubuntu_version: "20.04"
            llvm_version: 13
          - ubuntu_version: "20.04"
            llvm_version: 15
          - ubuntu_version: "20.04"
            llvm_version: 18
    name: "Image Build (Ubuntu ${{ matrix.ubuntu_version }}, LLVM ${{ matrix.llvm_version }})"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        name: Setup Docker BuildX system
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: (github.ref == 'refs/heads/master')
        # && (github.repository == 'ldc-developers/ldc-build-environments')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        name: Build image
        with:
          push: ${{ (github.ref == 'refs/heads/master') }}
          # && (github.repository == 'ldc-developers/ldc-build-environments')
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
            LLVM_VERSION=${{ matrix.llvm_version }}
          tags: liushuyu/ldc-build-environments:${{ matrix.ubuntu_version }}-${{ matrix.llvm_version }}
